### ISSUE TITLE
Cookie Header giving 500 error

### ISSUE THREAD

**Issue by BritishBenji** [SuperSonicHub1/TikTok-RSS#2]
Hey, sorry, me again. Cookie header seems to have expired again, I went to go scrape my own, and I found that I couldn't find the cookie value for the `R6kq3TV7` key?

Is there anywhere specific to find this to get this back up and running again?

**Comment by SuperSonicHub1** [comment]
Personally, what I do is open TikTok in a private session, open up DevTools, and take the value of the `Cookie` header.

I'm hoping to look at [`yt-dlp`](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/tiktok.py) in order to create a more permanent solution.

**Comment by SuperSonicHub1** [comment]
Should have this fix implemented by tomorrow!
