### ISSUE TITLE
How to install it and host it

### ISSUE THREAD

**Issue by amanijoseph87** [SuperSonicHub1/TikTok-RSS#5]
Am beginner i want this for my project, i want to test it how can i run this in replit and get acces to subdomain

**Comment by SuperSonicHub1** [comment]
https://docs.replit.com/programming-ide/running-github-repositories-replit and https://docs.replit.com/hosting/hosting-web-pages should be of use to you. Your `.replit` file should look like this:
```ini
lang = "python3"
run = "python3 main.py"
```

**Comment by amanijoseph87** [comment]
Can you add "Run on Replit" Badge for easy start

**Comment by SuperSonicHub1** [comment]
https://github.com/SuperSonicHub1/TikTok-RSS/commit/4061e08bca4a50787bcc46b509ceca47bf6d9532
https://github.com/SuperSonicHub1/TikTok-RSS/commit/c192f712509d8a2e59767b919ac651d7aceeb94a

Done.
