### ISSUE TITLE
Always runs into 404

### ISSUE THREAD

**Issue by Sagestum** [SuperSonicHub1/TikTok-RSS#6]
Hi, 
I have installed it on a new bionic installation with python3.8, but
sadly I only get a 404 in the end: 

` * Serving Flask app 'main' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:8080
 * Running on http://172.26.0.2:8080 (Press CTRL+C to quit)
95.223.3.222 - - [30/Apr/2022 03:27:51] "GET / HTTP/1.1" 200 -
95.223.3.222 - - [30/Apr/2022 03:27:51] "GET /favicon.ico HTTP/1.1" 302 -
95.223.3.222 - - [30/Apr/2022 03:27:56] "GET /lookup?q=Plankton HTTP/1.1" 302 -
95.223.3.222 - - [30/Apr/2022 03:27:57] "GET /feed/Plankton HTTP/1.1" 404 -
`
Maybe a TikTok related issue?

**Comment by SuperSonicHub1** [comment]
The account you've specified doesn't seem to exist:
https://www.tiktok.com/@Plankton
We 404 if that happens.
